export interface GirlProfile {
  profileId: string;
  type: "SWEET" | "COOL" | "POP" | "---";
  grade: "1年生" | "2年生" | "3年生" | "---";
  school: "聖櫻学園" | "嵯峨椿高校" | "鳳歌院高校" | "昇星高校" | "玉宮高校";
  clubType:
    | "委員会＆団体"
    | "運動部"
    | "運動部(個人競技)"
    | "帰宅部"
    | "研究会"
    | "文化部"
    | "文化部(音楽系)"
    | "文化部(日本)"
    | "設定なし";
}

export const NAME_TO_PROFILE_CONVERT: Record<string, GirlProfile> = {
  赤瀬川摩姫: {
    profileId: "32",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  朝門春日: {
    profileId: "194",
    type: "SWEET",
    grade: "3年生",
    school: "鳳歌院高校",
    clubType: "文化部(音楽系)",
  },
  朝比奈桃子: {
    profileId: "101",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  浅見景: {
    profileId: "85",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  "アネット・オルガ・唐澤": {
    profileId: "203",
    type: "SWEET",
    grade: "3年生",
    school: "嵯峨椿高校",
    clubType: "文化部(音楽系)",
  },
  天都かなた: {
    profileId: "111",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  甘利燈: {
    profileId: "104",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  綾小路美麗: {
    profileId: "37",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  荒井薫: {
    profileId: "83",
    type: "---",
    grade: "---",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  有栖川小枝子: {
    profileId: "112",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  石田いすき: {
    profileId: "109",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  伊勢崎郁歩: {
    profileId: "2",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  伊勢谷里都: {
    profileId: "11",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  一ノ瀬友恵: {
    profileId: "260",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "設定なし",
  },
  一色愛瑠: {
    profileId: "27",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  岩本樹: {
    profileId: "7",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  浮橋明日香: {
    profileId: "184",
    type: "SWEET",
    grade: "2年生",
    school: "昇星高校",
    clubType: "文化部(音楽系)",
  },
  江藤くるみ: {
    profileId: "16",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  円城寺小菊: {
    profileId: "22",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  大山真由里: {
    profileId: "56",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  緒川唯: {
    profileId: "15",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  小倉愛: {
    profileId: "6",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  押井知: {
    profileId: "117",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  音羽ユリ: {
    profileId: "84",
    type: "COOL",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  小野寺千鶴: {
    profileId: "53",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  織部千華: {
    profileId: "166",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  皆藤蜜子: {
    profileId: "9",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  加賀美茉莉: {
    profileId: "103",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  神楽坂砂夜: {
    profileId: "78",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  掛井園美: {
    profileId: "55",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  風町陽歌: {
    profileId: "120",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  上条るい: {
    profileId: "30",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  栢嶋乙女: {
    profileId: "123",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  川上瀬莉: {
    profileId: "25",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  川淵一美: {
    profileId: "124",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  神崎ミコト: {
    profileId: "21",
    type: "COOL",
    grade: "---",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  岸田稚慧: {
    profileId: "13",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  君嶋里琉: {
    profileId: "113",
    type: "COOL",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  桐山優月: {
    profileId: "19",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  霧生典子: {
    profileId: "68",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  久仁城雅: {
    profileId: "196",
    type: "COOL",
    grade: "3年生",
    school: "鳳歌院高校",
    clubType: "文化部(音楽系)",
  },
  久保田友季: {
    profileId: "82",
    type: "---",
    grade: "---",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  熊田一葉: {
    profileId: "54",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  "クロエ・ルメール": {
    profileId: "64",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  黒川凪子: {
    profileId: "52",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  小泉由佳: {
    profileId: "14",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  九重忍: {
    profileId: "100",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  小日向いちご: {
    profileId: "61",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  五代律: {
    profileId: "28",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  佐伯鞠香: {
    profileId: "71",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  酒井田夏海: {
    profileId: "236",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  相楽エミ: {
    profileId: "121",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  櫻井明音: {
    profileId: "43",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  笹原野々花: {
    profileId: "77",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  三条八重: {
    profileId: "204",
    type: "COOL",
    grade: "3年生",
    school: "嵯峨椿高校",
    clubType: "文化部(音楽系)",
  },
  椎名心実: {
    profileId: "65",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  鴫野睦: {
    profileId: "97",
    type: "COOL",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  重藤秋穂: {
    profileId: "50",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  東雲レイ: {
    profileId: "59",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  篠宮りさ: {
    profileId: "156",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  島田泉: {
    profileId: "4",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  白瀬つづり: {
    profileId: "119",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  白鳥詩織: {
    profileId: "45",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  不知火五十鈴: {
    profileId: "74",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  白水六花: {
    profileId: "235",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  鈴河凜乃: {
    profileId: "76",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  反町牡丹: {
    profileId: "183",
    type: "POP",
    grade: "3年生",
    school: "昇星高校",
    clubType: "文化部(音楽系)",
  },
  高崎瑠依: {
    profileId: "40",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  高良美海: {
    profileId: "209",
    type: "POP",
    grade: "2年生",
    school: "玉宮高校",
    clubType: "文化部(音楽系)",
  },
  高良美空: {
    profileId: "208",
    type: "POP",
    grade: "2年生",
    school: "玉宮高校",
    clubType: "文化部(音楽系)",
  },
  武内未美: {
    profileId: "138",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  橘響子: {
    profileId: "92",
    type: "SWEET",
    grade: "---",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  玉井麗巳: {
    profileId: "57",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  千代浦あやめ: {
    profileId: "122",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  月隈林子: {
    profileId: "238",
    type: "COOL",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  月白陽子: {
    profileId: "66",
    type: "COOL",
    grade: "---",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  藤堂静子: {
    profileId: "199",
    type: "COOL",
    grade: "---",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  遠山未涼: {
    profileId: "10",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  時谷小瑠璃: {
    profileId: "115",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  戸村美知留: {
    profileId: "70",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  豊永日々喜: {
    profileId: "202",
    type: "POP",
    grade: "3年生",
    school: "嵯峨椿高校",
    clubType: "文化部(音楽系)",
  },
  直江悠: {
    profileId: "185",
    type: "COOL",
    grade: "3年生",
    school: "昇星高校",
    clubType: "文化部(音楽系)",
  },
  奈木野さくら: {
    profileId: "237",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  夏目真尋: {
    profileId: "110",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  七海四季: {
    profileId: "164",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  鍋島ちより: {
    profileId: "5",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  成瀬まなみ: {
    profileId: "26",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  鳴海調: {
    profileId: "180",
    type: "SWEET",
    grade: "---",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  南條クミコ: {
    profileId: "31",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  新垣雛菜: {
    profileId: "41",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  西野彩音: {
    profileId: "23",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  新田萌果: {
    profileId: "47",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  螺子川来夢: {
    profileId: "80",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  長谷川美卯: {
    profileId: "24",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  畑山政子: {
    profileId: "102",
    type: "---",
    grade: "---",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  葉月柚子: {
    profileId: "99",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  羽鳥晶: {
    profileId: "35",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  花房優輝: {
    profileId: "179",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  林田希羅: {
    profileId: "36",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  林田たまき: {
    profileId: "3",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  早見英子: {
    profileId: "18",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  春宮つぐみ: {
    profileId: "79",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  柊真琴: {
    profileId: "20",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  東野梓: {
    profileId: "17",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  日野奏恵: {
    profileId: "1",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  飛原鋭子: {
    profileId: "73",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  姫島木乃子: {
    profileId: "63",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  深見絵真: {
    profileId: "176",
    type: "SWEET",
    grade: "---",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  芙来田伊吹: {
    profileId: "125",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  古谷朱里: {
    profileId: "69",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  前田彩賀: {
    profileId: "8",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(日本)",
  },
  牧瀬昴: {
    profileId: "195",
    type: "POP",
    grade: "2年生",
    school: "鳳歌院高校",
    clubType: "文化部(音楽系)",
  },
  正岡真衣: {
    profileId: "49",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  真白透子: {
    profileId: "200",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  三科果歩: {
    profileId: "88",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  三嶋ゆらら: {
    profileId: "116",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  "ミス・モノクローム": {
    profileId: "62",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  水野楓夏: {
    profileId: "12",
    type: "COOL",
    grade: "---",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  皆口英里: {
    profileId: "38",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  南田七星: {
    profileId: "48",
    type: "SWEET",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  宮内希: {
    profileId: "81",
    type: "POP",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "研究会",
  },
  見吉奈央: {
    profileId: "51",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  村上文緒: {
    profileId: "67",
    type: "COOL",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  望月エレナ: {
    profileId: "75",
    type: "SWEET",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  森園芽以: {
    profileId: "98",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  八束由紀恵: {
    profileId: "42",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  山田はな: {
    profileId: "39",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  山野こだま: {
    profileId: "44",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  優木苗: {
    profileId: "58",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  祐天寺弥生: {
    profileId: "172",
    type: "POP",
    grade: "---",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
  湯川基世: {
    profileId: "60",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  雪風真弥: {
    profileId: "33",
    type: "COOL",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  弓削楓: {
    profileId: "93",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  夢前春瑚: {
    profileId: "72",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  "ユーリヤ・ヴャルコワ": {
    profileId: "46",
    type: "SWEET",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "運動部",
  },
  吉川繭子: {
    profileId: "87",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  吉永和花那: {
    profileId: "168",
    type: "POP",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "文化部",
  },
  蓬田菫: {
    profileId: "148",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "文化部(音楽系)",
  },
  李春燕: {
    profileId: "34",
    type: "POP",
    grade: "2年生",
    school: "聖櫻学園",
    clubType: "運動部(個人競技)",
  },
  竜ヶ崎珠里椏: {
    profileId: "29",
    type: "COOL",
    grade: "1年生",
    school: "聖櫻学園",
    clubType: "帰宅部",
  },
  若林璃子: {
    profileId: "999",
    type: "---",
    grade: "3年生",
    school: "聖櫻学園",
    clubType: "委員会＆団体",
  },
} as const;
