name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: next-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: next-app

      - name: Build with Next.js
        run: npx next build
        working-directory: next-app
        env:
          NEXT_PUBLIC_DEPLOY_TARGET: github
          NEXT_PUBLIC_BASE_PATH: /kinokotogame.club

      - name: Image optimization
        run: npx next-export-optimize-images
        working-directory: next-app
        env:
          NEXT_PUBLIC_DEPLOY_TARGET: github
          NEXT_PUBLIC_BASE_PATH: /kinokotogame.club

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: next-app/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
